apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil-app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wil-app
  template:
    metadata:
      labels:
        app: wil-app
    spec:
      containers:
      - name: wil-app
        image: wil42/playground:v1
        ports:
          - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: wil-app
  namespace: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: wil-app

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inception-of-things-p3
spec:
  rules:
  - host:
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: wil-app
            port:
              number: 80
